### ISSUE TITLE
Aster回避後のwaypointsと回避前のwaypointsのindexの数が合わない

### ISSUE THREAD

**Issue by Alpaca-zip** [sbgisen/autoware_ai_planning#13]
**概要**
[astar_avoid.cpp](https://github.com/sbgisen/autoware_ai_planning/blob/master/waypoint_planner/src/astar_avoid/astar_avoid.cpp)において`state_ == AstarAvoid::STATE::AVOIDING`から`state_ == AstarAvoid::STATE::RELAYING`に戻る際に、`goal_waypoint_index`と`end_of_avoid_index`が一致しない。
https://github.com/sbgisen/autoware_ai_planning/blob/a9553172cdb642b8af8120ea10e553933754b91f/waypoint_planner/src/astar_avoid/astar_avoid.cpp#L367
https://github.com/sbgisen/autoware_ai_planning/blob/a9553172cdb642b8af8120ea10e553933754b91f/waypoint_planner/src/astar_avoid/astar_avoid.cpp#L315

**修正しないとどう困るか**
`updateClosestWaypoint()`にて`current_waypoints_`が`base_waypoints_`に変化した時に、indexのずれによって`closest_local_index`が-1になる場合がある。
https://github.com/sbgisen/autoware_ai_planning/blob/a9553172cdb642b8af8120ea10e553933754b91f/waypoint_planner/src/astar_avoid/astar_avoid.cpp#L447-L455
これが発生するとすべてのwaypointの中から最も近いwaypointを探すことになるので、経路がジャンプする原因となる。
[回避経路が出た際に別のwaypointに戻ってしまう #5](https://github.com/sbgisen/autoware_ai_planning/issues/5)

**修正案**
1. `goal_waypoint_index`と`end_of_avoid_index`が一致するようにastar_avoid.cpp内で調整する
[bugfix/aster_avoid_index](https://github.com/sbgisen/autoware_ai_planning/tree/bugfix/aster_avoid_index), [bugfix/waypoint_planner](https://github.com/sbgisen/autoware_ai_planning/tree/bugfix/waypoint_planner)にて作業中。
~~発生条件がAVOIDING->RELAYINGやAVOIDING->STOPPING->PLANNING->AVOIDING->RELAYINGなど複数存在しており、すべての条件分岐について網羅ができていない状況。~~
2. `current_waypoints_`を`base_waypoints_`に戻さず、`mergeAvoidWaypoints()`で更新される`avoid_waypoints_`を利用する
[bugfix/closest_waypoint_index](https://github.com/sbgisen/autoware_ai_planning/tree/bugfix/closest_waypoint_index)にて作業中。
常に線形にwaypointを追い続けることができるが、Asterで無理なpathが生成された際のリカバリが難しい。
2. `goal_waypoint_index`と`end_of_avoid_index`が一致するように`path.poses.size()`を変更できるようにする
未検証。
[astar_search.cpp](https://github.com/sbgisen/autoware_ai_planning/blob/master/astar_search/src/astar_search.cpp)を修正する必要あり。

**Comment by nyxrobotics** [comment]
[bugfix/waypoint_planner](https://github.com/sbgisen/autoware_ai_planning/pull/21)で検証しましたのでDraft PR出しておきます。indexの切り替え自体はうまく行くようになったと思います。
