### ISSUE TITLE
#14 で生じたバグの修正

### ISSUE THREAD

**Issue by nyxrobotics** [sbgisen/autoware_ai_planning#16]
**概要**
```lane_select```で実現したい動作は下記
- traffic_waypoints_arrayは１回のみ受取り、全体のwaypointを保持
- stop_waypoints_arrayを一定周期で受取り、信号機の色に応じて停止線付近のwaypointのvelocityを切り替え
  - 信号機の色によってstop_waypoints_arrayのtwistが切り替わる
  - stop_waypoints_arrayは複数の経路をarrayで保持しているので、そのなかから今乗っている経路を選択しbase_waypointsとしてパブリッシュする

![Screenshot from 2023-03-27 18-23-33](https://user-images.githubusercontent.com/19720932/227900588-b3c33033-392d-42f4-9bd5-2a385c1f8275.png)

問題点は下記
```is_new_array```が```true```のときのみ```base_waypoints```がパブリッシュされる
https://github.com/sbgisen/autoware_ai_planning/blob/2a79ae558f9a9659330994913fc80cf5971fb332/lane_planner/nodes/lane_select/lane_select_core.cpp#L168-L173

```callbackFromStopArray```で```is_new_array```を更新していないので、信号機の色が変わっても```base_waypoints```がパブリッシュされない
https://github.com/sbgisen/autoware_ai_planning/blob/2a79ae558f9a9659330994913fc80cf5971fb332/lane_planner/nodes/lane_select/lane_select_core.cpp#L642

これを修正すると```/light_color_managed```に```0```をパブリッシュすると停止線で止まり、```1```をパブリッシュすると再開するようになる。このときoutdoor_navigation_toolsのpythonスクリプトは全て不要。

- Reference #12 

**再現手順**
**修正しないとどう困るか**
**原因**
**修正案**

**Comment by nyxrobotics** [comment]
メモ
- lane_rule
  - ゴール地点で減速するように速度を置換して```green_waypoints_array```と```traffic_waypoints_array```をパブリッシュ（この２つの中身は同じ）
  -  ゴール地点で減速するのに加えて、一時停止線（stopline）と交差するwaypointの前後の一定範囲（number_of_zeros_ahead, number_of_zeros_behind）の速度を0、加速度一定（acceleration）で加減速するように速度を上書きして```red_waypoints_array```をパブリッシュ
- lane_stop
  - ```green_waypoints_array```と```red_waypoints_array```をサブスクライブし、```light_color_managed```で1を受け取ったときに```green_waypoints_array```、0を受け取ったときに```red_waypoints_array```の中身を```stop_waypoints_array```でパブリッシュする
- lane_select
  - ```stop_waypoints_array```の中でロボットから近い点を追従するように```closest_waypoint```を算出する
  - ```stop_waypoints_array```は配列になっていて複数のレーンを保持するのに対し、ここでは```closest_waypoint```が追従しているwaypointのみを取り出して```base_waypoints```をパブリッシュする
  - レーンを切り替える機能もここで実装されているようだが正確な使用方法は不明
- aster_avoid
  - ```base_waypoints```上に障害物があるときに回避経路を算出して```safety_waypoints```をパブリッシュ
  - 回避経路が見つからないときは前回の経路を保持
- velocity_set
  -  ```safety_waypoints```上に障害物があるとき、障害物付近で停止するように速度を上書きして```final_waypoints```をパブリッシュ
- pure_pursuit
  - ```final_waypoints```に追従するように```twist_raw``` をパブリッシュ

**Comment by Tacha-S** [comment]
的外れかもしれないですが、 #14 の時点でtopicを分けずに、`lane_array_id_` が変わった場合のみ`current_lane_idx_`, `right_lane_idx_`, `left_lane_idx_`をリセットするだけでよかったのではないですか？

**Comment by nyxrobotics** [comment]
> 的外れかもしれないですが、 #14 の時点でtopicを分けずに、`lane_array_id_` が変わった場合のみ`current_lane_idx_`, `right_lane_idx_`, `left_lane_idx_`をリセットするだけでよかったのではないですか？

結局```lane_select```は```traffic_waypoints_array```を使っていないので、サブスクライバを増やしたメリットはなく、```stop_waypoints_array```だけサブスクライブするようにしたほうが良かったということになります。
lane_array_id_が変わったときのみインデックスを初期化すればよいのも正しいです。

加えて、下記の```std::make_tuple```の第二引数で入っている-1についても`lane_array_id_` が変わっていないときは元の値を保持したい部分になります。
https://github.com/sbgisen/autoware_ai_planning/blob/2a79ae558f9a9659330994913fc80cf5971fb332/lane_planner/nodes/lane_select/lane_select_core.cpp#L628-L632

~なぜClosestWaypointのインデックスがすべてのウェイポイントで必要なのか不明のため調査中です。~
→それぞれのレーンの最近点を保持してレーン切替時に使用しているようです

**Comment by Tacha-S** [comment]
たしかにその`tuple_vec_`のindex保持しているところも`lane_array_id_`が変わっていないときは維持したいですね。

**Comment by nyxrobotics** [comment]
#14 をRevertして作業し直す方針にします

**Comment by Alpaca-zip** [comment]
> これを修正すると/light_color_managedに0をパブリッシュすると停止線で止まり、1をパブリッシュすると再開するようになる。このときoutdoor_navigation_toolsのpythonスクリプトは全て不要。

judge_stopline.pyとjudge_endpoint.pyは以下で、ロボットの速度が0であることを確認しています。

https://github.com/sbgisen/outdoor_navigation_tools/blob/ca18d0272fa64bd33d72c91762181e5d9c0bdda9/outdoor_navigation/scripts/judge_stopline.py#L80-L86

https://github.com/sbgisen/outdoor_navigation_tools/blob/ca18d0272fa64bd33d72c91762181e5d9c0bdda9/outdoor_navigation/scripts/judge_endpoint.py#L41-L47

このことから推測するに、これらのスクリプトはAutowareに何らかの司令を送るためのものではなく、単に一時停止線もしくは最後のウェイポイントに到達し、停止したかを知らせるための用途として作られたものではないかと思います。
なので、デバッグ用としてこれらのノードをlaunchファイル内で利用するかどうか、argで指定できるようにするのも手だと思います。
