### ISSUE TITLE
[aster_avoid]一回転以上する経路の除外

### ISSUE THREAD

**Issue by nyxrobotics** [sbgisen/autoware_ai_planning#24]
**概要**
下記のような、異常に迂回する経路を候補から除外するためのパラメータを追加したい
(表示されるwaypoitを増やすため```velocity_set/temporal_waypoints_size```を600にしています)
![Screenshot from 2023-04-13 21-13-55](https://user-images.githubusercontent.com/19720932/231755030-409763da-e512-4bf8-8907-f497fffaaef7.png)

**目的**
ステアリング機体のように、カーブの曲率に制限がある機体で異常な経路が発生しないようにするため

**提案内容**
上述のような経路の検出方法として以下２パターン考えられる
- 案1. asterで導出される経路の角度変化の絶対値の合計を使用し、一定よりカーブが多い経路は除外する
- 案2. asterで導出される経路の距離が一定より大きい経路は除外する
- 
asterの探索をしているのが下記の関数
https://github.com/sbgisen/autoware_ai_planning/blob/7ae0fb1264c9b6c0183e447eef09c4e9010a3291/astar_search/src/astar_search.cpp#L335

**追加パラメータ**
- ```enable_path_angle_limit```をtrueにすると回避経路の角度の総和を制限
- ```path_angle_limit```に設定された角度を超えるとasterの候補から外す
- ```enable_path_length_limit```をtrueにすると回避経路の経路長の制限
- ```path_length_limit```に設定された経路長を超えるとの候補から外す

**Comment by nyxrobotics** [comment]
asterの各ノード(コストマップのピクセル相当)に移動距離の総和を保持している部分があり、これを参照して移動角の総和を```move_angle```として保持できそうでした。

https://github.com/sbgisen/autoware_ai_planning/blob/b146776f67524bab8cbd4fec2b238a216fb55788/astar_search/include/astar_search/astar_util.h#L30-L39

https://github.com/sbgisen/autoware_ai_planning/blob/7ae0fb1264c9b6c0183e447eef09c4e9010a3291/astar_search/src/astar_search.cpp#L371-L376

また、現在の角度についても下記の```modifyTheta```を除去すると一回転を超える角度の変位を保持できました。
https://github.com/sbgisen/autoware_ai_planning/blob/7ae0fb1264c9b6c0183e447eef09c4e9010a3291/astar_search/src/astar_search.cpp#L374

異常な回避経路が出る場合、下記のようになっていました。
```bash
[ INFO] [1681386962.870332263, 2433.036000000]: Search time: 178.020483 [msec]
[ INFO] [1681386962.870369110, 2433.036000000]: move_distance= 27.096237,theta= -0.523599,move_angle= 12.304571
```

```bash
[ INFO] [1681387161.617272571, 2494.023000000]: Search time: 354.891578 [msec]
[ INFO] [1681387161.617320872, 2494.023000000]: move_distance= 36.992253,theta= -6.283185,move_angle= 15.184364
```
```bash
[ INFO] [1681389962.831056703, 3343.506000000]: Search time: 119.776609 [msec]
[ INFO] [1681389962.831107597, 3343.506000000]: move_distance= 28.981192,theta= -6.544985,move_angle= 12.304571
```
正常な経路で大きめにカーブする際は下記のようになっています
```bash
[ INFO] [1681387108.574585145, 2477.910000000]: Search time: 150.747498 [msec]
[ INFO] [1681387108.574643804, 2477.910000000]: move_distance= 12.252211,theta= -0.785398,move_angle= 6.283185
```

**Comment by nyxrobotics** [comment]
上記の例だと「経路の総和が20m超える」や「カーブの合計が3piラジアン以上」などの条件で絞れそうです。
また異常経路の２個めの例ではゴール地点に到達までに負の方向に１回転しています。

**Comment by nyxrobotics** [comment]
除外する場合はnodeをOPENにしなければasterで候補として利用されなくなるようです
https://github.com/sbgisen/autoware_ai_planning/blob/7ae0fb1264c9b6c0183e447eef09c4e9010a3291/astar_search/src/astar_search.cpp#L440
- 参考: https://qiita.com/2dgames_jp/items/f29e915357c1decbc4b7

**Comment by nyxrobotics** [comment]
最短で一回転する経路の場合は下記でした。
これを防ぐ場合はthetaが2pi超える場合も例外にする必要あり
```bash
[ INFO] [1681390944.898855030, 3714.048000000]: Search time: 114.942496 [msec]
[ INFO] [1681390944.898893280, 3714.048000000]: move_distance= 16.728981,theta= -6.675884,move_angle= 7.984881
```

![Screenshot from 2023-04-13 22-04-15](https://user-images.githubusercontent.com/19720932/231767390-e9aad991-ea46-4ae1-8602-96ab01b772d5.png)

**Comment by nyxrobotics** [comment]
```prohibit_circulation```フラグで2piを超える経路を除外するようにしたが、ギリギリ2piより小さい経路が発生する
![Screenshot from 2023-04-13 23-06-02](https://user-images.githubusercontent.com/19720932/231784675-a2c52e18-8339-4c84-94c0-652dca080100.png)

スレッショルドを変数にして1.75pi程度にすればおよそ解消できると思います（網羅的か怪しい）

**Comment by Tacha-S** [comment]
> 最短で一回転する経路の場合は下記でした。
これを防ぐ場合はthetaが2pi超える場合も例外にする必要あり

このケースは後退を禁止していてwayarea的に左に最小旋回半径で回っても周り切れなさそうなので最善手ではないですか？

全体的に`angle_goal_range`の条件を満たすために旋回しているように見えるので、
実機のステアリング改善されたのであれば`angle_goal_range`をオーバーシュートしないギリギリまで上げてみたりはしましたか？

**Comment by nyxrobotics** [comment]
> 

ゴール地点に対しては最善手だと思います。あとはゴール地点が更に前方なら旋回せず回避できる経路が出ると思います。
現状aster avoidが手前から順に回避経路を算出するようになっているので、例外で無視すれば次の候補(先の地点)をゴールとして再計算します。
ただ角度そのもので絞るのはアルゴリズム的に汎用性が低いので```prohibit_circulation_```と```circulation_angle_limit_```は消し、ゴール地点を前にオフセットする方法で回避したほうが良いかもしれません。
(angle_goal_rangeは30[deg]にしています。)
