### ISSUE TITLE
[aster_avoid] curve_weightが使われていない

### ISSUE THREAD

**Issue by nyxrobotics** [sbgisen/autoware_ai_planning#29]
**概要**
asterで回避経路を算出する際にカーブの少ない経路を優先的に選択するためのパラメータと見られる```curve_weight```  について、
パラメータだけ定義されていて使われていない。

https://github.com/sbgisen/autoware_ai_planning/blob/b146776f67524bab8cbd4fec2b238a216fb55788/astar_search/src/astar_search.cpp#L37

本家の最新でも同じ状況(asterからはパラメータも消えている)
https://github.com/autowarefoundation/autoware.universe/blob/388d36e924297d58e94328c18b9948b01cd2ea61/planning/freespace_planning_algorithms/include/freespace_planning_algorithms/abstract_algorithm.hpp#L92
https://github.com/autowarefoundation/autoware.universe/blob/f321e40c02328f9d7ad6ec7c6a210e1a53e6b369/planning/freespace_planner/src/freespace_planner/freespace_planner_node.cpp#L303

**修正案**
```reverse_weight```が下記のように実装されており、同様の手順で探索時のコストを増やせば実装できそう
https://github.com/sbgisen/autoware_ai_planning/blob/b146776f67524bab8cbd4fec2b238a216fb55788/astar_search/src/astar_search.cpp#L378-L380

**Comment by nyxrobotics** [comment]
初期値1でデフォルト動作、１より大きいと直進を優先する

- 案１
  - 角度変化に応じてコストを追加する

```cpp
      // Increase curve cost
      double curve_cost = fabs(state.rotation) * (curve_weight_- 1.0);
      move_cost += curve_cost;
```

- 案２
  - `reverse_weight_`と同様に倍率でコストを掛ける
```cpp
      // Increase curve cost
      double curve_cost_scale = 1.0 + (fabs(state.rotation) * (curve_weight_ - 1.0));
      move_cost *= curve_cost_scale;
```

**Comment by nyxrobotics** [comment]
他に案あればコメントいただけると幸いです

**Comment by nyxrobotics** [comment]
案２の方法でカーブの少ない経路を選択するような挙動を確認できたので、#30 でドラフトのPR作成しました。有効性を確認できたらDraft解除する予定です。

**Comment by Tacha-S** [comment]
A*はダイクストラと根本的な部分は変わらないので負のコストが発生するのは良くない(解が正しくなくなったり、無限ループに陥る可能性がある)のでそこだけ気をつけたほうがいいです。
