### ISSUE TITLE
waypointの高さがロボットとズレているときz軸方向に刻んで補間される

### ISSUE THREAD

**Issue by nyxrobotics** [sbgisen/autoware_ai_planning#40]
**概要**
ロボットの現在位置から最近傍点までを補間する間隔にz軸成分が含まれているが
車両型ロボットは上下方向には移動しないのでxy成分のみで見て一定間隔で補間したい
local waypointが短くなっている気がするので要検証（短くなっていたら直したい）
![Screenshot from 2023-10-05 16-45-56](https://github.com/sbgisen/autoware_ai_planning/assets/19720932/b89eedc0-c03f-4f24-a3b7-f1a0e18b156f)
![Screenshot from 2023-10-05 16-45-57](https://github.com/sbgisen/autoware_ai_planning/assets/19720932/c9b894bb-0ce8-4b1c-b8c4-4ced97626964)

**再現手順**
**修正しないとどう困るか**
**原因**
**修正案**

**Comment by nyxrobotics** [comment]
Asterの回避経路はz=0（localizationが2dモードなのでロボットの高さがz=0）に出る。このときは特に問題なし
![Screenshot from 2023-10-05 16-45-58](https://github.com/sbgisen/autoware_ai_planning/assets/19720932/e61fbc7a-7e3c-47ab-8724-53e8a46a8f53)

**Comment by nyxrobotics** [comment]
下記のdz成分を無視すればよいと思われる
local waypointが短くなっているように感じるのは気のせいかもしれない
https://github.com/sbgisen/autoware_ai_planning/blob/35e4b839c0dddfa4788f71f8f576c853b2e1ac04/waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp#L644-L648
↓
```double distance = sqrt(pow(dx, 2) + pow(dy, 2));```

**Comment by nyxrobotics** [comment]
`temporal_waypoints_size`が補間した点の数も数えている
→zがずれているときにlocal_waypointsが短くなっています

**Comment by Alpaca-zip** [comment]
https://github.com/sbgisen/autoware_ai_planning/pull/45 にて対応いただきましたので、こちらのissueは閉じさせていただきます。
