### ISSUE TITLE
赤信号で止まった後に青信号の司令を送っても動き出さない

### ISSUE THREAD

**Issue by Tacha-S** [sbgisen/autoware_ai_planning#6]
**概要**

青信号の司令は受け取れている(経路の速度の色が変わる)が
複数経路がチャタリングしているように見えた。
原因不明のため要調査

**再現手順**
**修正しないとどう困るか**
**原因**
**修正案**

**Comment by Alpaca-zip** [comment]
該当の問題が発生した信号の手前では、竹芝オフィスを一周回って帰ってくるウェイポイントとタリーズコーヒーの前を一周して帰ってくるウェイポイントの２つの経路が重なっています。

<img src="https://user-images.githubusercontent.com/84959376/225490384-bd2ee435-12fc-40fe-86f9-ab73c4bab39c.png" width="300px">

[publishWaypoints()](https://github.com/sbgisen/autoware_ai_planning/blob/f4633fbe7c40b108fba525c13a7ef6f866ab6b09/waypoint_planner/src/astar_avoid/astar_avoid.cpp#L370-L427)の中で、`closest_waypoint_index_`を表示させて検証をしていたところ、信号の手前で２つのウェイポイントを頻繁にジャンプしていました。そのため、竹芝オフィスを一周回って帰ってくるウェイポイントに乗っているタイミングでは、その先のウェイポイントが存在しないため信号が青であったとしても進めなかったのではないかと思われます。

![Screenshot from 2023-03-16 10-51-56](https://user-images.githubusercontent.com/84959376/225491657-eeecc246-4d06-453b-80cf-96278a1b4a30.png)
![Screenshot from 2023-03-16 10-51-33](https://user-images.githubusercontent.com/84959376/225491667-e253f171-a1aa-45d6-b6b4-fa6fc10e6ac5.png)

**Comment by Alpaca-zip** [comment]
[bugfix/closest_waypoint_index](https://github.com/sbgisen/autoware_ai_planning/tree/bugfix/closest_waypoint_index)ブランチを利用してrosbag検証を行うと、信号手前でウェイポイントがジャンプする現象は確認されなくなりました。一度、実機で動かして挙動を確認してみたいと思います。

**Comment by Tacha-S** [comment]
これに関しては #5 が解決すれば発生しなさそうということで一旦closeしようと思います。
また、再発するようであればそのときreopenします。
